---
title: "Untitled"
output: html_document
---

練習
```{r}
load(url("https://www.dropbox.com/s/qnz9paigf61yjus/commitHistory.Rda?raw=1"))
```
任務0：print「每個」commit的author等於committer的邏輯判斷結果。

sequence source
```{r}
commitHistory
```
body
print「第i個」commit的author等於committer的邏輯判斷結果。
```{r}
i <- 1

(commitHistory[[i]][["commit"]][["author"]][["name"]]==commitHistory[[i]][["commit"]][["committer"]][["name"]]) -> logiResult
print(logiResult)
```
for loop
```{r}
for(i in seq_along(commitHistory)){
  (commitHistory[[i]][["commit"]][["author"]][["name"]]==
     commitHistory[[i]][["commit"]][["committer"]][["name"]]) ->
    logiResult
  print(logiResult)  
}
```
任務一：存下來每個commit的author。
```{r}
load(url("https://www.dropbox.com/s/qnz9paigf61yjus/commitHistory.Rda?raw=1"))
```
0. saving container
```{r}
saveCommitAuthor <-
  vector("character",length(commitHistory))
```
1. sequence source
```{r}
commitHistory
```
2. body
存下來「第i個」commit的author。
```{r}
i<- 1

commitHistory[[i]]$commit$author$name -> saveCommitAuthor[[i]]
```
檢查一下
```{R}
saveCommitAuthor
```
3. for loop
```{R}
saveCommitAuthor <-
  vector("character",length(commitHistory)) # 0.
for(i in seq_along(commitHistory)){
  commitHistory[[i]]$commit$author$name -> saveCommitAuthor[[i]]
}

saveCommitAuthor
```