---
title: "Untitled"
output: html_document
---

name()
```{r}
Vector1 <- letters[1:6]
Vector1

names(Vector1)
```
```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```

新增/替換元素
```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在
a
```
```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)

b$元素3 <- FALSE
b[[5]] <- 7
b
```

使用"元素名稱"創新元素
```{r}
names(b)
b[["新元素A"]] <- c(1,2,3)
b$新元素B <- c(T,F,T)
b
```

練習
```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```
取出「期間」變數轉成date class
```{r}
library(lubridate)
exData3$期間 <- ymd(exData3$期間)
class(exData3$期間)
```
增加一個「isAsiaCrisis」的logical變數，其值為TRUE若「期間」介於1997-06-01到1998-12-01（含前後）
```{r}
exData3$isAsiaCrisis <- (exData3[[1]] >= ymd("1997-06-01") & exData3[[1]] <= ymd("1998-12-01"))
class(exData3$isAsiaCrisis)
```

練習
```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```
取出92aS67fee子樣本
```{r}
transcriptDataFinal[transcriptDataFinal$學號 == "92aS67fee",]
```

