---
title: "Untitled"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lubridate)
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

顯示時區
```{r}
Sys.timezone()
```

改成台灣時區
```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
```

轉成Europe/Lisbon時區，""理面也可以填時區代碼，如WET，GMT
```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
```

typeof得知電腦存成什麼樣的數值，as.強迫他顯示該務實際數值
```{r}
typeof(twDateTime)
as.double(twDateTime)
as.double(LisbonDateTime)
as.integer(twDateTime)
```

其他種日期顯示模式
只用年月日存的數值是幾"天"
```{r}
library(lubridate)
dtObject<-ymd("2018-09-11")
typeof(dtObject)
as.double(dtObject)
as.double(ymd("2018-09-11"))
```

數值運算
```{r}
a <- c(1, 5, -3)
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
c<-4
aL+bL
a+bL
aL/bL
aL+c
class(aL+bL)
class(a+bL)
class(aL-bL)
twDateTime
twDateTime+1
```


```{r}
twDateTime1<-ymd("2018-09-15")
twDateTime2<-ymd("2018-09-16")
twDateTime2-twDateTime1
```

加一年的寫法差異
```{r}
startingDate <- ymd("2000-02-17")
startingDate + years(1)
startingDate + dyears(1)
```

數值間的關係
```{r}
x <- 5
y <- 7

x >= y
x == y
x <= y
```

x = y 與 x <- y 相同
```{r}
x = y
as.integer(x)
```

==(等於)和!=(不等於)亦可用字串
```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
x3 == y3
x3 != y3
```

%in%為屬於的概念
```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4
y4 %in% x4
```

NA間無法作邏輯比較
```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")

x2 == y2
x3 == y3
x2 + NA
sum(x2)
```

用is.na函數得知該物裡面是否有NA
```{r}
is.na(x2)
is.na(x3)
```