---
title: 'untitled'
output: html_document
---

```{r}
textbookURL <- function(){
  browseURL("https://bookdown.org/tpemartin/ntpu-programming-for-data-science/")
}
```

無input,return
cat指顯示在螢幕上
為return所以xx是沒有東西的
```{r}
library(lubridate)

now2 <- function(){
  currentDateTime <- Sys.time()
  hh<-hour(currentDateTime)
  mm<-minute(currentDateTime)
  cat("現在是",hh,"點",mm,"分")
}
```
```{r}
now2()
now2() <- xx
xx
```

輸出多個函數要用list
```{r}
demand_supply_fun <- function(P,a,b,c,d){
  QS <- a + b*P
  QD <- c - d*P
  return(
    list(
      供給量 = QS,
      需求量 = QD,
      超額供給量 = QS - QD
    )
  )
}
```
```{r}
demand_supply_fun(1,2,3,4,5)
```

條件執行
print和message皆為訊息顯示，但message是用在出現錯誤時的訊息顯示
```{r}
supply_fun1 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P不能為負值") # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else {
    return(Qs)
  }
}
supply_fun1(P=-1,0,1)
supply_fun1(P=2,0,1)
```
```{r}
gpa_fun <- function(studentID){
  if(studentID %in% transcriptDataFinal$學號){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  subSample <- transcriptDataFinal[logiChosenStudent,]
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
  }
  else
    {
      message("查無此學號")
    }
}

gpa_fun("92aS67fee") # 顯示82.85276
gpa_fun("aa829838s") # 查無此學號
```

