---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

!negation
```{r}
x <- 5
y <- 7

x == y
!(x == y)
```

```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
currency <- exData2$幣別
```

```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
date <- as.character(exData2$期間)
currency <- exData2$幣別
exchangeRate <- exData2$匯率
```

head可用來觀測物件的前6筆值
```{r}
head(currency)
```

資料一進來並沒有被當成是factor
```{r}
class(currency)
```

更正成factor
```{r}
currency <- as.factor(currency)
class(currency)
```

用levels看類別(只有factor物件能看種類，類別)
```{r}
levels(currency)
```

length數向量內的元素個數(向量長度)
```{r}
length(levels(currency))
```

多少筆日圓資料
```{r}
sum(currency == "日圓JPY/USD")
```

%in%，&，|，用法
```{r}
x5 <- c("台北市","新北市","高雄市")
greatTaipei <- c("台北市","新北市")

x5 %in% greatTaipei
!(x5 %in% greatTaipei)
```
```{r}
y5 <- c("女","男","女")

y5
y5=="女"
!(y5=="女")
```
```{r}
(x5 %in% greatTaipei) & (y5=="女")
```
```{r}
(x5 %in% greatTaipei) | (y5=="女")
```
```{r}
xor(x5 %in% greatTaipei, y5=="女")
```

練習
```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
date <- as.character(exData2$期間)
currency <- exData2$幣別
exchangeRate <- exData2$匯率
```
原本是charactor
```{r}
class(date)
```
發現是時間資料
```{r}
head(date)
```
安裝lubridate
```{r}
library(lubridate)
date <- ymd(date)
```
屬性變成Date
```{r}
class(date)
```
1980-08-01之後的資料有多少筆
(date要跟同屬性(Date)的比大小)
```{r}
isAfter19080801 <-
  date >= ymd("1980-08-01")
head(isAfter19080801)
head(as.integer(date))
as.integer(ymd("1980-08-01"))
sum(isAfter19080801)
```
幣別為歐圓的有多少筆
```{r}
head(currency == "歐元USD/EUR")
sum(currency == "歐元USD/EUR")
```



