---
title: "Untitled"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```

[[.]]取一個元素
```{r}
plasticContainer

plasticContainer[["greenBox"]] 
plasticContainer[[1]]
```
```{r}
plasticContainer[["greenBox"]][[1]]
```
```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord
```
```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)
```
```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)
成績單[[1]]
```
```{r}
studentRecord[["姓名"]]
studentRecord[["學年平均成績"]][[3]]
```

[.]取一群元素
```{r}
plasticContainer[c("greenBox","redBox")] 
plasticContainer[c(1,2)]
```

[]會保有a母層的元素(在例題中為塑膠箱)，[[]]則不會
```{r}
plasticContainer

extract1 <- plasticContainer[c("greenBox")]
extract1
extract2 <- plasticContainer[[c("greenBox")]]
extract2

extract1[[1]]
extract1[[1]][[1]]
extract2[[1]]
```






































