---
title: "Untitled"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
randomGrades <- sample(40:80,15,replace = T)
randomCredits <- sample(0:3,15,replace=T)
data3 <- list(
  成績=randomGrades,
  學分數=randomCredits
)
```

```{r}
data3
passLogic <- data3$成績>=60
passLogic2 <- passLogic == TRUE
passLogic2
a <- data3$成績[passLogic2]
a
passData <- list(
  成績 = data3$成績[passLogic == T],
  學分數 = data3$學分數[passLogic == TRUE]
)
passData
```

Ans51
```{r}
sample(99:103,15,replace = T)-> yy
sample(1:12,15,replace=T)-> mm
str_c("民國",str_pad(yy,3,"left","0"),"年",mm,"月") -> twDates
twDates
 str_replace(twDates,"民國","") -> x1
x1
str_replace(x1,"月","") -> twDates2
twDates2
 str_replace_all(twDates,"(民國)|(月)","")
```

Ans52
```{r}
twDates
str_sub(twDates,3,5) -> yearCharacter
yearCharacter
 as.integer(yearCharacter)+1911 -> westYears
westYears
```

Ans53
```{r}
twDates2
str_split(twDates2,"年") -> datesSplitList # 用年切開 年 月值
datesSplitList

map(datesSplitList,~.[[2]]) -> monthList # 選出每個元素的第二個值
monthList

unlist(monthList) -> monthVector # 將list疊成字串向量
monthVector

str_c(as.character(westYears),monthVector,"01",sep = "-") -> westDates # 貼成YYYY-MM-DD 字串格式
westDates

ymd(westDates) -> westDates # 轉成dates
westDates
class(westDates)
```

Ans71
```{r}
(sampledTranscriptData$科目名稱 == "科目204") -> logicChosenSubject
length(logicChosenSubject)
sum(logicChosenSubject)
(sampledTranscriptData$科目名稱 == "科目204" & 
    sampledTranscriptData$學期成績 < 60) -> logicChosenSubjectAndFail
length(logicChosenSubjectAndFail)
sum(logicChosenSubjectAndFail)
sum(logicChosenSubjectAndFail)/sum(logicChosenSubject) -> failRate
failRate
```

Ans72
```{r}
sampledTranscriptData$學屆 <- 
  str_sub(sampledTranscriptData$學號,2,4)
sampledTranscriptData$系碼 <- 
  str_sub(sampledTranscriptData$學號,5,6)
tail(sampledTranscriptData$學號) # or head()
tail(sampledTranscriptData$系碼) # or head()
#sampledTranscriptData
```

Ans73
```{r}
sampledTranscriptData$學系 <- str_replace(sampledTranscriptData$系級,"1","")
sampledTranscriptData$學系 <- str_replace(sampledTranscriptData$學系,"2","")
sampledTranscriptData$學系 <- str_replace(sampledTranscriptData$學系,"3","")
sampledTranscriptData$學系 <- str_replace(sampledTranscriptData$學系,"4","")

head(sampledTranscriptData$系級)
head(sampledTranscriptData$學系)
## ----ans73---------------------------------------------------------------
sampledTranscriptData$學系 <- str_replace(sampledTranscriptData$系級,"[1234]","")

sampledTranscriptData$學系
## ----ans73---------------------------------------------------------------
sampledTranscriptData$學系 <- str_replace(sampledTranscriptData$系級,"[:digit:]","")

sampledTranscriptData$學系
```

